//  Auth Actions
export const ISCANCELLED = "ISCANCELLED";
export const LOGIN_FAIL = "LOGIN_FAILED";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGOUT = "LOGOUT";
export const LOAD_USER_DETAILS = "LOAD_USER_DETAILS";
export const REGISTER_USER = "REGISTER_USER";
export const TOKEN_VALIDATION = "TOKEN_VALIDATION";
export const LOGIN_USER = "LOGIN_USER";
export const SET_USER_AVATAR_COLOR = "SET_USER_AVATAR_COLOR";

