# Generated by Django 4.2.17 on 2025-01-21 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('premedication', models.JSONField()),
                ('treatment_plan', models.JSONField()),
                ('diet_plan', models.JSONField()),
                ('not_to_eat', models.JSONField()),
            ],
        ),
    ]
